import {
  Home,
  LayoutDashboard,
  LayoutGrid,
  Compass,
  Search,
  Bookmark,
  Pin,
  Link as LinkIcon,
  ExternalLink,
  ArrowUpRight,
  Bell,
  Settings,
  HelpCircle,
  Shield,
  Zap,
  CalendarCheck,
  ListTodo,
  Target,
  Rocket,
  Coins,
  BadgeDollarSign,
  DollarSign,
  Gift,
  Ticket,
  Trophy,
  Award,
  Medal,
  Crown,
  Star,
  Sparkles,
  Flame,
  Percent,
  ClipboardPlus,
  Gamepad2,
  Puzzle,
  Brain,
  GraduationCap,
  BookOpen,
  Lightbulb,
  PlayCircle,
  Video,
  Tv,
  Music,
  Headphones,
  Camera,
  Image as ImageIcon,
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  Receipt,
  ShoppingBag,
  Store,
  Package,
  Briefcase,
  Megaphone,
  BarChart3,
  Users,
  User,
  Handshake,
  MessageSquare,
  Heart,
  Share2,
  Hash,
  Newspaper,
  Globe,
  MapPin,
  Smartphone,
  Layers,
  FileText,
  type LucideIcon,
} from "lucide-react";
import { createElement, type ComponentProps } from "react";
import type { NavIconKey } from "@/lib/nav-icon-keys";

export { NAV_ICON_OPTIONS, isNavIconKey, type NavIconKey } from "@/lib/nav-icon-keys";

/**
 * Key → lucide component for every icon an admin can pick on a navigation
 * surface. `satisfies Record<NavIconKey, …>` makes the compiler refuse a key
 * listed in `nav-icon-keys.ts` with no component here, and vice versa.
 */
export const NAV_ICONS = {
  home: Home,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  compass: Compass,
  search: Search,
  bookmark: Bookmark,
  pin: Pin,
  link: LinkIcon,
  externalLink: ExternalLink,
  arrowUpRight: ArrowUpRight,
  bell: Bell,
  settings: Settings,
  helpCircle: HelpCircle,
  shield: Shield,
  zap: Zap,
  calendarCheck: CalendarCheck,
  listTodo: ListTodo,
  target: Target,
  rocket: Rocket,
  coins: Coins,
  badgeDollar: BadgeDollarSign,
  dollar: DollarSign,
  gift: Gift,
  ticket: Ticket,
  trophy: Trophy,
  award: Award,
  medal: Medal,
  crown: Crown,
  star: Star,
  sparkles: Sparkles,
  flame: Flame,
  percent: Percent,
  clipboardPlus: ClipboardPlus,
  gamepad: Gamepad2,
  puzzle: Puzzle,
  brain: Brain,
  graduation: GraduationCap,
  bookOpen: BookOpen,
  lightbulb: Lightbulb,
  playCircle: PlayCircle,
  video: Video,
  tv: Tv,
  music: Music,
  headphones: Headphones,
  camera: Camera,
  image: ImageIcon,
  wallet: Wallet,
  creditCard: CreditCard,
  banknote: Banknote,
  piggyBank: PiggyBank,
  receipt: Receipt,
  shopping: ShoppingBag,
  store: Store,
  package: Package,
  briefcase: Briefcase,
  megaphone: Megaphone,
  barChart: BarChart3,
  users: Users,
  user: User,
  handshake: Handshake,
  messageSquare: MessageSquare,
  heart: Heart,
  share: Share2,
  hash: Hash,
  newspaper: Newspaper,
  globe: Globe,
  mapPin: MapPin,
  smartphone: Smartphone,
  layers: Layers,
  fileText: FileText,
} satisfies Record<NavIconKey, LucideIcon>;

/** The component for a stored key; an unknown key draws `fallback`. */
export function navIcon(key: string | null | undefined, fallback: LucideIcon = Zap): LucideIcon {
  return (key && (NAV_ICONS as Record<string, LucideIcon>)[key]) || fallback;
}

/**
 * Render a stored icon key. A component rather than `const I = navIcon(k)`
 * inside render, which the React compiler lint reads as a component created
 * during render.
 */
export function NavIcon({
  iconKey,
  fallback = Zap,
  ...props
}: { iconKey: string | null | undefined; fallback?: LucideIcon } & ComponentProps<LucideIcon>) {
  return createElement(navIcon(iconKey, fallback), props);
}
