ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "requireApp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "requirePush" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "announcedAt" TIMESTAMP(3);
