-- Site popups: video / HTML content, second button, size, and more audience rules.
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "videos" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "htmlCode" TEXT;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "htmlHeight" INTEGER NOT NULL DEFAULT 320;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "cta2Label" TEXT;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "cta2Url" TEXT;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "size" TEXT NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "planAudience" TEXT NOT NULL DEFAULT 'ANY';
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "packageIds" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "minLevel" INTEGER;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "maxLevel" INTEGER;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "minAccountDays" INTEGER;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "maxAccountDays" INTEGER;
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "devices" TEXT[] DEFAULT ARRAY[]::TEXT[];
