-- Banner audience targeting (same columns as Task / TaskBoard) + KYC audience.
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "countries" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "genders" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "regions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "divisions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "districts" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "subDistricts" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "postalCodes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "minAge" INTEGER;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "maxAge" INTEGER;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "kycAudience" TEXT NOT NULL DEFAULT 'ANY';
